import Colors from "../../utils/colors";
const styles = {
  yellowButtonStyle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "14px 20px",
    borderRadius: "10px",
  },
  primaryButtonStyle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "6px 14px",
    borderRadius: "6px",
    background: Colors.primary,
  },
  primaryButtonTableStyle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "6px 14px",
    fontSize: "14px",
    fontWeight: "500",
    borderRadius: "6px",
    background: Colors.primary,
    color: "white",
  },
  whiteButtonStyle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "14px 20px",
    borderRadius: "10px",
    border: "1px solid #D0D5DD",
    background: Colors.white,
    boxShadow: "0px 1px 2px 0px rgba(16, 24, 40, 0.05)",
  },
  whiteButtonTableStyle: {
    color: Colors.subtitleText,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "6px 14px",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "500",
    border: "1px solid #D0D5DD",
    boxShadow: "0px 1px 2px 0px rgba(16, 24, 40, 0.05)",
  },
  fontStyle: {
    fontSize: "16px",
    fontWeight: "500",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "100%",
  },
};
export default styles;
