export const ClientData = [
  {
    name: "Cody Fisher",
    company: "McDonald's",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    project: "12",
    spent: "$120k",
    subscription: "Pro",
  },
  {
    name: "Cody Fisher",
    company: "McDonald's",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    project: "12",
    spent: "$120k",
    subscription: "Standard",
  },
  {
    name: "Cody Fisher",
    company: "McDonald's",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    project: "12",
    spent: "$120k",
    subscription: "Pro",
  },
  {
    name: "Cody Fisher",
    company: "McDonald's",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    project: "12",
    spent: "$120k",
    subscription: "Pro",
  },
  {
    name: "Cody Fisher",
    company: "McDonald's",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    project: "12",
    spent: "$120k",
    subscription: "Pro",
  },
  {
    name: "Cody Fisher",
    company: "McDonald's",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    project: "12",
    spent: "$120k",
    subscription: "Pro",
  },
  {
    name: "Cody Fisher",
    company: "McDonald's",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    project: "12",
    spent: "$120k",
    subscription: "Pro",
  },
  {
    name: "Cody Fisher",
    company: "McDonald's",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    project: "12",
    spent: "$120k",
    subscription: "Pro",
  },
  {
    name: "Cody Fisher",
    company: "McDonald's",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    project: "12",
    spent: "$120k",
    subscription: "Pro",
  },
  {
    name: "Cody Fisher",
    company: "McDonald's",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    project: "12",
    spent: "$120k",
    subscription: "Pro",
  },
];
