const pricingData = [
  {
    id: "1",
    badge: "Most popular",
    name: "Standard",
    subtitle: "One request at a time. Pause or cancel anytime.",
    pricing: "4999",
    currency: "USD",
    paymentMethod: "monthly",
    subHeading: "Pause or cancel anytime.",
    status: "active",
    features: [
      "One request at a time",
      "Three brands",
      "Unlimited users",
      "Unlimited stock photos via Shutterstock or Freepik",
      "Easy credit-card payments",
      "Pause or cancel anytime",
    ],
  },

  {
    id: "2",
    badge: "",
    name: "Pro",
    subtitle: "Double the requests. Pause or cancel anytime.",
    pricing: "9999",
    currency: "USD",
    paymentMethod: "monthly",
    subHeading: "Pause or cancel anytime.",
    status: "inactive",
    features: [
      "Two requests at a time",
      "Average 48 hour delivery",
      "Unlimited brands",
      "Unlimited users",
      "Unlimited stock photos via Shutterstock or Freepik",
      "Easy credit-card payments",
      "Pause or cancel anytime",
    ],
  },
  {
    id: "3",
    badge: "",
    name: "Platinum",
    subtitle: "Double the requests. Pause or cancel anytime.",
    pricing: "14999",
    currency: "USD",
    paymentMethod: "monthly",
    subHeading: "Pause or cancel anytime.",
    status: "inactive",
    features: [
      "Two requests at a time",
      "Average 48 hour delivery",
      "Unlimited brands",
      "Unlimited users",
      "Unlimited stock photos via Shutterstock or Freepik",
      "Easy credit-card payments",
      "Pause or cancel anytime",
    ],
  },
];

export default pricingData;
