const settingsTeamData = [
  {
    _id: "adfhdsfsd",
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    _id: "adfhdsdssf",
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    _id: "adfhdsdssf",
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    _id: "adfhdsgrewtf",
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    _id: "adfhd2desfsf",
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    _id: "adferfhdsf",
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    _id: "adfhdsuiuf",
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    _id: "adfyutghdsf",
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    _id: "adfhrtdsf",
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    _id: "adfhdsrtrhf",
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
];
export default settingsTeamData;
