const settingsTeamData = [
  {
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
  {
    name: "Md Mohiuddin",
    email: "mohiuddin@gmail.com",
    role: "Engineering Lead (Backend)",
    about: "as sdfgd fgs dfgae rtg sdfg sdfg sertg dfg ert xadsda sd asdasd a",
    tasks: [
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
      {
        name: "Catalog Design",
        priority: "High",
        status: "In Progress",
        assignedAt: "01/27/2023",
        dueBy: "01/27/2023",
      },
    ],
  },
];
export default settingsTeamData;
