export const TeamData = [
  {
    name: "Aman Ullah",
    designation: "Sr. Integrated Design Specialist",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    projectAssigned: "12",
    role: "Designer",
    address: "123,A,fdsf,asdqwer",
  },
  {
    name: "Md Golam Rabbi",
    designation: "MERN Stack Web Developer",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    projectAssigned: "12",
    role: "Web Developer",
    address: "123,A,fdsf,asdqwer",
  },
  {
    name: "Md Mohiuddin",
    designation: "Sr. Integrated Design Specialist ",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    projectAssigned: "12",
    role: "Designer",
    address: "123,A,fdsf,asdqwer",
  },
  {
    name: "Aman Ullah",
    designation: "Sr. Integrated Design Specialist ",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    projectAssigned: "12",
    role: "Designer",
    address: "123,A,fdsf,asdqwer",
  },
  {
    name: "Aman Ullah",
    designation: "Sr. Integrated Design Specialist ",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    projectAssigned: "12",
    role: "Designer",
    address: "123,A,fdsf,asdqwer",
  },
  {
    name: "Aman Ullah",
    designation: "Sr. Integrated Design Specialist ",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    projectAssigned: "12",
    role: "Designer",
    address: "123,A,fdsf,asdqwer",
  },
  {
    name: "Aman Ullah",
    designation: "Sr. Integrated Design Specialist ",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    projectAssigned: "12",
    role: "Designer",
    address: "123,A,fdsf,asdqwer",
  },
  {
    name: "Aman Ullah",
    designation: "Sr. Integrated Design Specialist ",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    projectAssigned: "12",
    role: "Designer",
    address: "123,A,fdsf,asdqwer",
  },
  {
    name: "Aman Ullah",
    designation: "Sr. Integrated Design Specialist ",
    number: "(704) 555-0127",
    email: "quasiah@gmail.com",
    projectAssigned: "12",
    role: "Designer",
    address: "123,A,fdsf,asdqwer",
  },
];
